### PR TITLE
Add typedefs and update deps

### PR DESCRIPTION
**Pull request by Nicholaiii**
This PR contains two changes:
Adding TypeScript definition file, and bumping all deps.

I understand there's a good few changes, but I thought I might as well update deps as well. Feel free to ask any questions, or flat out reject parts. Here's an outline of all substantial changes contained:

- Add `index.d.ts`. This is a minimal implementation, ideally we would reference the libraries themselves, but this plays nice. 
- Update essentially all deps.
- Migrate Husky 4 to 7, this involves moving config from `package.json` to `.husky/`
- Update `index.js` to pass linter requirements, specifically import `process` instead of relying on globals, and convert `Array#forEach` to `for...of`
- Bump minor version. This PR adds features, but backwards compatibly, so I thought it fitting according to SEMVER.

### CODE REVIEW

**Review by shadowgate15 — COMMENTED** [review]
Can you adjust the functions return to `Promise<void>` instead of `any`?

It is good practice not to include `any` in type definitions.

**Comment by niftylettuce** [comment]
Thanks for the PR @Nicholaiii! See @shadowgate15 comments above.  As a side note, you could hook up https://nicholai.dev/ with https://forwardemail.net 😄

**Comment by Nicholaiii** [comment]
I agree with the sentiment, but this would be a breaking change. 
Also, [`net.Server.close()`](https://nodejs.org/api/net.html#serverclosecallback) returns the instance of `Server`, not `Promise<void>`.
Generally I decided to err on the side of caution, importing Server from `node:http` would have been sane, but not assuredly backwards compatible. 

I think the type-safer, non-breaking alternative is using `unknown`

Edit: Also, just to be clear, I'm not saying breaking changes **must** be avoided, rather that I didn't feel this would be my call.

**Comment by shadowgate15** [comment]
I think I would be okay with using `unknown` instead of `void`.

**Comment by Nicholaiii** [comment]
This should do the trick. 
Edit: I can wrap up typedefs and also add timeoutMs and logger option if you wish.

**Comment by shadowgate15** [comment]
@Nicholaiii that would be good and also make the returns `Promise<unknown>` not just unknown.

**Comment by Nicholaiii** [comment]
> 
> 
> @Nicholaiii that would be good and also make the returns `Promise<unknown>` not just unknown.

I cannot do it across the board. ioredis does not return a Promise, neither does http/net.Server and customHandlers never required a Promise, so existing users might not be passing async functions to it. It doesn't really add any typesafety to force it to be a Promise, you can `await` any arbitrary values (not just Promises), so whatever the return value of any function the lib depends on, it won't break.
I think it's safe to add `Promise<void>` for bree and mongoose in particular because their types already export this definition, but for the rest it's better kept as unknown to avoid breaking builds.

**Comment by Nicholaiii** [comment]
Here we go. I think this is as full as it gets without setting up a full ts pipeline.

**Comment by shadowgate15** [comment]
@niftylettuce this is good

**Pull request merged**
